# Generated by Django 5.0.3 on 2024-04-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="asd", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="asd", verbose_name="Описание товара"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(
                default="asd", max_length=50, verbose_name="Имя товара"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default="asd", unique=True, verbose_name="Slug товара"
            ),
            preserve_default=False,
        ),
    ]
